export const GET_MOVIE_GENRE_REQUEST = 'GET_MOVIE_GENRE_REQUEST';
export const GET_MOVIE_GENRE_SUCCESS = 'GET_MOVIE_GENRE_SUCCESS';
export const GET_MOVIE_GENRE_FAILURE = 'GET_MOVIE_GENRE_FALIURE';

export const SET_PAGE = 'SET_PAGE';
export const GET_ALL_MOVIES_REQUEST = 'GET_ALL_MOVIES_REQUEST';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILURE = 'GET_ALL_MOVIES_FALIURE';

export const GET_MOVIE_DETAIL_REQUEST = 'GET_MOVIE_DETAIL_REQUEST';
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const GET_MOVIE_DETAIL_FAILURE = 'GET_MOVIE_DETAIL_FALIURE';